### ISSUE TITLE
Query all objects of an event

### ISSUE THREAD

**Issue by lichtamberg** [seatsio/seatsio-ruby#1]
Hi,

first of all, thank you very much for providing a ruby gem for your API, this will save time for us, since we don't have to handle all the http stuff by our selfes!

Right now it looks pretty fine, the only thing which we are missing right now is to get a list of all objects, with extraData included in each object. As far as I saw there is no API call for this available?

**Comment by nahue** [comment]
Please refer to https://docs.seats.io/docs/api-detailed-reports. You will get extraData from the detailed reports.
Let us know if this solved your problem.

**Comment by lichtamberg** [comment]
Ah, didn't see that one, thank you!

**Comment by nahue** [comment]
Thank you @lichtamberg and please do not hesitate on providing more feedback! we really appreciate it.
