### ISSUE TITLE
Allow editing of handicap accessible category attribute?

### ISSUE THREAD

**Issue by dsgraham** [seatsio/seatsio-ruby#12]
When I retrieve the published version of chart, in the category list there is a boolean `accessible` key. However, when **updating** a chart's categories this key is not permitted:
```
Seatsio::Exception::SeatsioException (
  {"status": 400,
   "messages": [
       "#/categories/0: extraneous key [accessible] is not permitted",
       "#/categories/1: extraneous key [accessible] is not permitted"],
   "errors": [
       {"code": "GENERAL_ERROR",
        "message": "#/categories/0: extraneous key [accessible] is not permitted"},
       {"code": "GENERAL_ERROR",
        "message": "#/categories/1: extraneous key [accessible] is not permitted"}],
   "warnings": [],
   "requestId": "fee5171f-cc3f-4535-9deb-0bbbc5c06ca3"}
)
```
I am managing seat categories external to Seats.io and would love to be able to offer a handicap accessible option on my ticket categories.

**Comment by mroloux** [comment]
Yes, that makes sense. Changing the accessibility of a category is not something we support right now, but I'll let you know when we do.

**Comment by mroloux** [comment]
You can now update the accessible flag of a category. Thanks for reporting this!
