### ISSUE TITLE
https://docs.seats.io/docs/api-best-available ruby example shows invalid parameter names

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [seatsio/seatsio-ruby#15]
The example in the docs for the ruby client is wrong, since it shows the first two keys (event key and size) as named parameters/hash keys, but if you look at the code, they are just normal unnamed parameters.

I think the documentation should be updated accordingly.

```ruby
client.events.book_best_available key: 'event1', number: 10, categories: ['balcony', 'stalls']
```

https://github.com/seatsio/seatsio-ruby/blob/ca36c9cc1cd422f20cc39f4e6cfa4b1e7efd754c/lib/seatsio/events.rb#L78

Thanks!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Also it seems that you can't provide any extraData, like mentioned in the docs?

**Comment by nahue** [comment]
Hello! thanks for pointing that out, i updated the docs.

About extraData, we will put that in our todo's list, so i will keep this issue open until we fix that.
