### ISSUE TITLE
Handling empty chart lists

### ISSUE THREAD

**Issue by patmisch** [seatsio/seatsio-ruby#2]
When fetching a list of charts for a subaccount that does not have any created yet, the client returns NoMethodErrors for all routine enumerable methods. A request for all charts when there are none seems to result in nil rather than an empty collection. 

Alternatively, Is there an easy way to quickly see if the account does have any charts created yet?

**Comment by nahue** [comment]
Hello, @patmisch thanks for your feedback!
I'm currently fixing the enumerable so it returns an empty array if there are no results, would that work for you?

To test if the account does not have any charts you can try the following

```ruby
client.charts.list.to_a.empty?
```

(That will work after i release this fix ofcourse)

**Comment by patmisch** [comment]
Yes, perfect. Thanks for the prompt reply!

**Comment by nahue** [comment]
Sorry for the delay! can you please upgrade to version 3 and try again?

**Comment by patmisch** [comment]
Looks good to me. Thanks for quick fix.
