### ISSUE TITLE
Ruby 3-related deprecation error-- Proc without a block

### ISSUE THREAD

**Issue by DanL12186** [seatsio/seatsio-ruby#43]
Running Ruby 3.0 or later, the `Pagination::Cursor/#each` method becomes a problem.

line 33 in `cursor.rb` I believe is the only place the issue is present, but trying to iterate over a collection of seats objects results in a `tried to create Proc object without a block` error.

**Comment by bverbeken** [comment]
Hey Daniel,

Fixed in [v35.1.1](https://github.com/seatsio/seatsio-ruby/releases/tag/v35.1.1)

Thanks for reporting! 🙏
