### ISSUE TITLE
Auto-generate changelogs on new releases

### ISSUE THREAD

**Issue by jonahgeorge** [seatsio/seatsio-ruby#67]
Would you please consider [auto-generating release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)? It makes it substantially easier to review dependency upgrades on Github when paired with Dependabot.

Currently one must navigate to the repo and then manually compare the tags:
![CleanShot 2023-03-13 at 08 22 19](https://user-images.githubusercontent.com/2058205/224746987-dc15663e-cc22-4264-80d5-352881fcdb71.png)

Compared to:
![CleanShot 2023-03-13 at 08 24 29](https://user-images.githubusercontent.com/2058205/224747607-623eec04-d24c-40e9-bd60-7e39fe9ed89d.png)

**Comment by schaloner** [comment]
@jonahgeorge Thanks for the suggestion.  We will start using this for all our clients in the future.

**Comment by jonahgeorge** [comment]
Awesome! Thank you
