### ISSUE TITLE
Development dependency "rest-client" seems to be required for production usage.

### ISSUE THREAD

**Issue by Caleb-T-Owens** [seatsio/seatsio-ruby#72]
Hi! I've been utilising the seatsio-ruby library to interact with the Seats API. In the gemspec the gem "rest-client" is listed as a development dependency https://github.com/seatsio/seatsio-ruby/blob/1e5b657855ce10dd4cda1423e7432005fb8a960b/seatsio.gemspec#L26 but it's required and used inside httpClient.rb https://github.com/seatsio/seatsio-ruby/blob/1e5b657855ce10dd4cda1423e7432005fb8a960b/lib/seatsio/httpClient.rb#L1 and the library won't function without it, with us having to include it in our Gemfile alongside the seatsio-ruby gem.

It would be good if rest-client was moved to be a full dependency of the seatsio gem. It does also seem that the rest-client gem is unmaintained currently and might be worth considering migrating to a different HTTP client. https://github.com/rest-client/rest-client/issues/764

**Comment by mroloux** [comment]
Ah yes, good point. We moved that dependency to the runtime dependencies in https://github.com/seatsio/seatsio-ruby/releases/tag/v43.2.0

And good point about `rest-client` not being maintained anymore. We'll look into an alternative.

**Comment by Caleb-T-Owens** [comment]
Thanks!
